# Generated by Django 4.2.7 on 2023-11-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profedor',
            new_name='Profesor',
        ),
    ]
