# Generated by Django 4.2.7 on 2023-11-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_rename_profedor_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nombre',
            new_name='curso',
        ),
    ]
